engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 120
ratings:
  paths:
  - src/js/**
  - src/scss/**
  - "**.js"
exclude_paths:
- src/tests/**/*
